name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.5.3<4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
